### ISSUE TITLE
Not able to use your action due to a fatal error

### ISSUE THREAD

**Issue by dianjuar** [CasperWA/push-protected#59]
I'm getting the following error.

```bash
fatal: You are not currently on a branch.
```

Here you can get the full error
https://github.com/bikecoders/ngx-deploy-npm/runs/4121319485?check_suite_focus=true

And this is my workflow config file
```yml
name: Experiment
on:
  push:
    branches:
      - push-to-protected-branches
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup

      - name: git config
        shell: bash
        run: |
          git config user.name "Github Actions"
          git config user.email "-"
      - name: Version and Publishment
        run: npx nx version-preliminar --dry-run false

      - name: Tag last-release
        run: git tag -f last-release

      - name: Push to protected branch
        uses: CasperWA/push-protected@v2
        with:
          token: ${{ secrets.DELETEME_JUST_A_TEST }}
          branch: ${{ github.ref }}
          tags: true
          unprotect_reviews: true
```
